Remove unused management command urlstats Django management command format seems to have changed, and this command is broken:
CommandError: Error: unrecognized arguments: work4

Since it's actually unused, I'm simply going to remove it.